config/routes.rb
MackOverflow::Application.routes.draw do

  root :to => 'questions#index'  # We suggest to create a root to point to the sign in/create account page instead of having it pointing to questions#index

  resources :sessions, only: [:new, :create, :destroy]
  match '/signin', to: 'sessions#new'
  match '/signout', to: 'sessions#destroy'

  resources :questions, except: [:edit]

  resources :users, except: [:index]

  resources :answers, except: [:index]

  resources :users do 
    resources :questions, :only => [:show]
  end

  resources :users do 
    resources :answers, :only => [:show]
  end

  post '/questions/:id/answers', to: 'answers#create'

  post '/votes/create'

  resources :tags
end

app/models/answer.rb
class Answer < ActiveRecord::Base
  attr_accessible :content, :rating, :user_id

  belongs_to :user
  belongs_to :question
  has_many :votes, as: :votable
  validates_presence_of :content

  def set_rating
    upvote_count = self.votes.where(:is_upvote => true).count
    downvote_count = self.votes.where(:is_upvote => false).count
    self.rating = upvote_count - downvote_count
    self.save
  end

end

app/models/question.rb
class Question < ActiveRecord::Base
  attr_accessible :content, :rating, :user_id, :tag_list
  validates :user_id, presence: true

  belongs_to :user
  has_many :answers
  has_many :taggings
  has_many :tags, through: :taggings
  has_many :votes, as: :votable
  validates_presence_of :content

  def set_rating
    q = self
    upvote_count = q.votes.where(:is_upvote => true).count
    downvote_count = q.votes.where(:is_upvote => false).count
    q.rating = upvote_count - downvote_count
    q.save
    p q.rating
  end

  def tag_list
    tags.join(', ')
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(",").collect{|s| s.strip.downcase}.uniq
    new_or_found_tags = tag_names.collect { |name| Tag.find_or_create_by_name(name) }
    self.tags = new_or_found_tags
  end

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name

  has_many :taggings
  has_many :questions, through: :taggings


  def to_s
    name
  end

end

app/models/tagging.rb
class Tagging < ActiveRecord::Base
  belongs_to :tag
  belongs_to :question
end

app/models/user.rb
class User < ActiveRecord::Base

  has_secure_password

  validates_presence_of :password, :on => :create
  validates :username, :uniqueness => true

  attr_accessible :username, :password
  has_many :questions
  has_many :answers
  has_many :votes
end

app/models/vote.rb
class Vote < ActiveRecord::Base

  attr_accessible :is_upvote, :votable_id, :votable_type, :user_id
  validate :only_vote
  validates :user_id, presence: true

  belongs_to :user
  belongs_to :question
  belongs_to :answer
  belongs_to :votable, polymorphic: true
  after_save :update_count

  def update_count
    self.votable.set_rating
  end

  def only_vote
    unless Vote.where(votable_id: self.votable_id, votable_type: self.votable_type, user_id: self.user_id).empty?
      errors.add(:vote, "You can only vote once per item")
    end
  end
  
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

	def create
		
		@question = Question.find(params[:id])
		if logged_in?
			@answer = Answer.new(params[:answer])
			@answer.user = current_user
			@answer.question = @question
			@answer.save
		end

		redirect_to @question
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  helper_method :current_user, :logged_in?, :login, :logout

  def current_user
    @current_user ||= User.find_by_id(session[:user_id])
  end

  def logged_in?
    current_user.present?
  end

  def login(user)
    session[:user_id] = user.id
  end

  def logout
    session.clear
    flash[:notice] = "You have successfully logged out."
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  def index
    @questions_sorted_by_popularity = Question.all.sort_by { |question| question.answers.count }.reverse
    @questions = @questions_sorted_by_popularity.each
  end

  def new
    if logged_in?
      @question = Question.new
    else
      redirect_to root_path
    end
  end

  def create
    @question = Question.new(params[:question])
    @question.user = current_user
    if @question.save
      redirect_to question_path(@question)
    else
      render 'new'
    end
  end

  def show
    @question = Question.find(params[:id])
    @answers = @question.answers
  end
end



def question_params
  params.require(:question).permit(:content, :tag_list)
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  
  def new

  end

  def create
    user = User.find_by_username(params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      login user  
      redirect_to user
    else
      # Create an error message and re-render the signin form 
      flash.now[:error] = "Invalid email/password combination"
      render 'new'
    end
  end

  def destroy
    logout
    redirect_to root_url
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController

  def index
    def index
    @tags = Tags.all
  end
  end

  def show
    @tag = Tag.find(params[:id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user= User.new(params[:user])
    if @user.save
      login(@user)
      redirect_to @user
    else
      flash[:notice] = @user.errors.full_messages  
      redirect_to new_user_path 
    end   
  end

  def show
    @user = User.find(params[:id])
    @questions = @user.questions.all
    @answers = @user.answers.all
  end



  def edit
    @answers =  Answer.new
    @user = User.new
  end

  # def update
    
  # end

end

app/controllers/votes_controller.rb
class VotesController < ApplicationController

  def create
    vote = Vote.new(is_upvote: params[:vote])
    q = params[:votableType].classify.constantize.find(params[:objectID])
    q.votes << vote
    vote.user_id = current_user.id
    vote.save
    q.reload
    q.rating
    render json: {value: q.rating}
  end
  
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/answers/_form.html.erb
<%= form_for(@answer) do |f| %>
  <% if @answer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@answer.errors.count, "error") %> prohibited this answer from being saved:</h2>

      <ul>
      <% @answer.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/answers/edit.html.erb
<h1>Editing answer</h1>

<%= render 'form' %>

<%= link_to 'Show', @answer %> |
<%= link_to 'Back', answers_path %>

app/views/answers/index.html.erb
<h1>Listing answers</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @answers.each do |answer| %>
  <tr>
    <td><%= link_to 'Show', answer %></td>
    <td><%= link_to 'Edit', edit_answer_path(answer) %></td>
    <td><%= link_to 'Destroy', answer, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Answer', new_answer_path %>

app/views/answers/new.html.erb
<h1>New answer</h1>

<%= render 'form' %>

<%= link_to 'Back', answers_path %>

app/views/answers/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_answer_path(@answer) %> |
<%= link_to 'Back', answers_path %>

app/views/layouts/_header.html.erb
	<nav>
	
			<%= link_to "Home", root_path %>
			<% if logged_in? %>
					<%= link_to "Ask a Mack for help", new_question_path %>
				<%= link_to "Sign out", signout_path, method: "delete" %>
			<% else %>
				<%= link_to "Sign in", signin_path %>
			  <%= link_to "Sign Up!", new_user_path %>

			<% end %>
	
	</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>MackOverflow</title>
  <link href='http://fonts.googleapis.com/css?family=Sansita+One' rel='stylesheet' type='text/css'>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= render 'layouts/header' %>
  <%= yield %>

</body>
</html>

app/views/questions/_form.html.erb
<%= form_for @question do |f| %>
  <%= f.text_area :content %>

  <p>
  <%= f.label :tag_list %>
  <%= f.text_field :tag_list %>
</p>

  <%= f.submit "Ask it!" %>
<% end %>

app/views/questions/_vote_box.html.erb
<div class="answer_box">
  

  <div class="upvote" id="<%= votable.id %>">
    <img style = "width: 20px" src="/upvote.png">
  </div>  

  <div class="rating">
    <%= votable.rating %>
    
  </div>

  <div class="downvote" id="<%= votable.id %>">
    <img style = "width: 20px" src="/downvote.png">
  </div>

</div>  

app/views/questions/edit.html.erb
<h1>Editing question</h1>

<%= render 'form' %>

<%= link_to 'Show', @question %> |
<%= link_to 'Back', questions_path %>

app/views/questions/index.html.erb
<div id="welcome">MackOverflow</div>

<div class="question_container">
<% @questions.each do |question| %>

	<div class="question">

    <%= render partial: "vote_box", locals: {:votable => question} %>
    <div class="qtitle">
      <%= link_to question.content, question %>
    </div>
    <span class="author"> Author: <%= link_to question.user.username, question.user %></span>
    <span class="author">Posted <%= time_ago_in_words(question.created_at) %> ago</span>

  </div>

<% end %>
</div>

app/views/questions/new.html.erb
<h1>Ask-a-Mack</h1>


Ask a Question
<%= render "form" %>


<%= link_to 'Back', questions_path %>

app/views/questions/show.html.erb
<p id="notice"><%= notice %></p>


<h2> Question: <%= @question.content %></h2>
<p>
  Tags:
  <% @question.tags.each do |tag| %>
    <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>

<div class="answer_container">
<h3>Answers</h3>
  <% @answers.each do |answer| %>
  	<div class="answer">

    <%= render partial: "vote_box", locals: {:votable => answer} %>
    <div class="answer_text">
      <%= answer.content %></p> 
    </div>
     <span class="author">Posted <%= time_ago_in_words(answer.created_at) %> ago</span>
     </div>
  <% end %>
</div>


<h4>Answer this question</h4>

<%= form_for(:answer, url: "/questions/#{@question.id}/answers") do |f| %>

  <%= f.text_field :content %>

  <%= f.submit "Answer!" %>
<% end %>

app/views/tags/index.html.erb
<h1>All Tags</h1>
<ul id='tags'>
  <% @tags.each do |tag| %>
  <li>
    <%= link_to tag.name, tag_path(tag), 
    class: 'tag_name' %> 
  </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Questions Tagged with <%= @tag.name %></h1>

<ul>
  <% @tag.questions.each do |question| %>
    <li><%= link_to question.content, question_path(question) %></li>
  <% end %>
</ul>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.label :username %>
    <%= f.text_field :username %>

    <%= f.label :password %>
    <%= f.password_field :password %>

    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @users.each do |user| %>
  <tr>
    <td><%= link_to 'Show', user %></td>
    <td><%= link_to 'Edit', edit_user_path(user) %></td>
    <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= flash[:notice] %>

<%= render 'form' %>

<%= link_to 'Back', root_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
<% if !@questions.empty? %>
  <h3>Your posted questions:</h3>
  <% @questions.each do |question| %>
    <h5><%= question.content %> (:Karma:) <%= question.rating %></h5>
    <%= link_to "Edit question", question_path %>
  <% end %>
<% else %>
  <h4>You have not posted any questions yet!</h4>
<% end %>
<% if !@answers.empty? %>
  <h3>Your posted answers:</h3>
  <% @answers.each do |answer| %>
    <h5><%= answer.content %> (:Karma:) <%= answer.rating %></h5>
  <% end %>
<% else %>
  <h4>You have not posted any answers yet!</h4>
<% end %>



<%= link_to 'Back', root_path %>